---
title: "97 Final"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(broom)
library(gt)


raw_data <- readxl::read_xlsx("formatted/country_Set.xlsx") %>% 
  clean_names() %>%
  rename(country = country_name) # for joining purposes

pop <- readxl::read_xlsx("formatted/WPP2019_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES.xlsx") %>%
  clean_names()
```


```{r data cleaning}

joined <- left_join(raw_data, pop, by = "country") %>%
  select(-variant, -index) %>%
  rename(population = x2020) %>%
  mutate(location_total = kfc_locations + mcd_locations) %>%
  mutate(nvp = as.numeric(nvp),
         naap = as.numeric(naap),
         wa = as.numeric(wa),
         wsa = as.numeric(wsa),
         wsd = as.numeric(wsd),
         wd = as.numeric(wd)) %>%
  mutate(ns_total = vp + qp + nvp + naap,
         gcs_total = wsa + wa + wd + wsd) %>%
  mutate(ns = (4*vp + 3*qp + 2*nvp)/ns_total,
         gcs = (4*wsa + 3*wa + 2*wd)/gcs_total) %>%
  mutate(lpm = (location_total/population)*1000) %>% # only multiplying by 1000 because populations are already divided by 1000
  select(country, ns, gcs, unfavorable, favorable, lpm)


regions <- readxl::read_xlsx("formatted/regions.xlsx") %>%
  clean_names() %>%
  rename(country = name) %>%
  select(country, region, sub_region) %>%
  drop_na()

data <- left_join(joined, regions, by = "country") %>%
  filter(lpm < 40)

```


```{r nationalism plot}

ns_plot <- data %>%
  drop_na(lpm, ns) %>%
  ggplot(aes(y = lpm, x = ns, color = region)) +
  geom_point() +
  geom_smooth(method = "glm", se = FALSE, fullrange = TRUE) +
  geom_smooth(method = "glm", level = 0, aes(group = 1), color = "black") +
  theme_classic() + 
  labs(title = "Nationalism vs. American Fast Food Footprint",
       subtitle = "Higher Nationalism Score (NS) corresponds with higher levels of nationalism",
       y = "MCD & KFC Locations per Million Residents",
       x = "Nationalism Score (NS)",
       color = "Region",
       caption = "\nData from the World Values Survey, KFC, and McDonald's")

ns_plot

```


```{r, gcs plots}

gcs_plot <- data %>%
  drop_na(lpm, gcs) %>%
  ggplot(aes(y = lpm, x= gcs, color = region)) +
  geom_point() +
  geom_smooth(method = "glm", se = FALSE, fullrange = TRUE) +
  geom_smooth(method = "glm", level = 0, aes(group = 1), color = "black") +
  theme_classic() + 
  labs(title = "World Citizenship vs. American Fast Food Footprint",
       subtitle = "Higher WCS corresponds with stronger feelings of world citizenship",
       y = "McDonald's and KFC Locations per Million Residents",
       x = "World Citizen Score (WCS)",
       color = "Region",
       caption = "\nData from the World Values Survey, KFC, and McDonald's")



```


```{r, gcs models}

# overall gcs model
gcs_all <- data %>%
  do(lm(lpm ~ gcs, data=.) %>% 
  tidy(conf.int = TRUE) %>%
  select(term, estimate, p.value, conf.low, conf.high)) %>%
  ungroup(region) %>%
  rename(Term = term, Estimate = estimate, "P-Value" = p.value, 
         "Upper Bound" = conf.high, "Lower Bound" = conf.low) 

# gcs by country model
gcs_by_country <- data %>%
  group_by(region) %>%
  do(lm(lpm ~ gcs, data=.) %>% 
  tidy(conf.int = TRUE) %>%
  select(term, estimate, p.value, conf.low, conf.high)) %>%
  ungroup(region) %>%
  rename(Region = region, Term = term, Estimate = estimate, "P-Value" = p.value, 
         "Upper Bound" = conf.high, "Lower Bound" = conf.low) 

# rounding function I ripped off stackoverflow lol
round_df <- function(df, digits) {
  nums <- vapply(df, is.numeric, FUN.VALUE = logical(1))
  df[,nums] <- round(df[,nums], digits = digits)
  (df)
}

# applying
gcs_by_country <- round_df(gcs_by_country, 2)
gcs_all <- round_df(gcs_all, 2)
  
```

```{r, ns models}

# overall gcs model
ns_all <- data %>%
  do(lm(lpm ~ ns, data=.) %>% 
  tidy(conf.int = TRUE) %>%
  select(term, estimate, p.value, conf.low, conf.high)) %>%
  ungroup(region) %>%
  rename(Term = term, Estimate = estimate, "P-Value" = p.value, 
         "Upper Bound" = conf.high, "Lower Bound" = conf.low) 

# gcs by country model
ns_by_country <- data %>%
  group_by(region) %>%
  do(lm(lpm ~ ns, data=.) %>% 
  tidy(conf.int = TRUE) %>%
  select(term, estimate, p.value, conf.low, conf.high)) %>%
  ungroup(region) %>%
  rename(Region = region, Term = term, Estimate = estimate, "P-Value" = p.value, 
         "Upper Bound" = conf.high, "Lower Bound" = conf.low) 

# rounding
ns_by_country <- round_df(ns_by_country, 2)
ns_all <- round_df(ns_all, 3)


```


```{r, US Sentiment}

# uss plot
uss_plot <- data %>%
  drop_na(lpm, favorable) %>%
  ggplot(aes(y = lpm, x = favorable, color = region)) +
  geom_point() +
  geom_smooth(method = "glm", se = FALSE, fullrange = TRUE) +
  geom_smooth(method = "glm", level = 0, aes(group = 1), color = "black") +
  theme_classic() + 
  labs(title = "US Favorability vs. American Fast Food Footprint",
       y = "McDonald's and KFC Locations per Million Residents",
       x = "US Percent Favorability (NS)",
       color = "Region",
       caption = "\nData from the Pew Research Center, KFC, and McDonald's")


# create model
uss_by_country <- data %>%
  group_by(region) %>%
  drop_na(lpm, favorable) %>%
  do(lm(lpm ~ favorable, data=.) %>% 
  tidy(conf.int = TRUE) %>%
  select(term, estimate, p.value, conf.low, conf.high))

uss_all <- data %>%
  drop_na(lpm, favorable) %>%
  do(lm(lpm ~ favorable, data=.) %>% 
  tidy(conf.int = TRUE) %>%
  select(term, estimate, p.value, conf.low, conf.high))

# round
uss_by_country <- round_df(uss_by_country, 2)
uss_all <- round_df(uss_all, 2)

```

```{r converting to word tables}

write_csv(gcs_by_country, "formatted/gcs_by_country.csv")
write_csv(gcs_all, "formatted/gcs_all.csv")
write_csv(ns_by_country, "formatted/ns_by_country.csv")
write_csv(ns_all, "formatted/ns_all.csv")
write_csv(uss_by_country, "formatted/uss_by_country.csv")
write_csv(uss_all, "formatted/uss_all.csv")

ggsave("formatted/gcs_plot.png", plot = gcs_plot, width = 8, height = 6)
ggsave("formatted/ns_plot.png", plot = ns_plot, width = 8, height = 6)
ggsave("formatted/uss_plot.png", plot = uss_plot, width = 8, height = 6)


```




